### ISSUE TITLE
Create user roles

### ISSUE THREAD

**Issue by csakiistvan** [drupalironcamp/campsite-2015#1]
We need some user roles:
- Manager admin
- Editor
- Attendee

**Comment by miromichalicka** [comment]
Working on this

**Comment by csakiistvan** [comment]
@miromichalicka on this commit, @Sweetchuck add 2 role, so please add to Attendee role, and the issue will fixed. https://github.com/drupalironcamp/campsite-2015/commit/9ae7b0b328f7a070093fcdd53bdcbccf1483493f
