### ISSUE TITLE
Update dates of attendance in user profile 

### ISSUE THREAD

**Issue by miromichalicka** [drupalironcamp/campsite-2015#104]
Currently, we have in user profile Monday-Friday as conference days, we need to update this to Thursday-Sunday.
<img width="305" alt="screen shot 2016-03-17 at 2 12 59 pm" src="https://cloud.githubusercontent.com/assets/1741875/13847259/92d4dd22-ec4c-11e5-9e7b-c6a9055b0164.png">

**Comment by mojzis** [comment]
This issue was moved to drupalironcamp/website#6
