### ISSUE TITLE
Clean up spam accounts on live site

### ISSUE THREAD

**Issue by radimklaska** [drupalironcamp/campsite-2015#105]
There is bunch of spam accounts on live site. We should clean this up and prevent new creation of new ones.
- maybe just a core setting since only users with valid ticket should have an account
- not all blocked account seem to be spam, see /user/200

**Comment by miromichalicka** [comment]
I wouldn't block registrations without valid ticket, because we want people to submit their session proposals. I often do that without ticket.

**Comment by mojzis** [comment]
This issue was moved to drupalironcamp/website#5
