### ISSUE TITLE
Fix Twitter box in footer

### ISSUE THREAD

**Issue by zsofimajor** [drupalironcamp/campsite-2015#107]
It looks like Twitter changed something, therefore the twitter box doesn't look nice anymore. It should be fixed to match the designs.

**Comment by klukacin** [comment]
@zsofimajor I can't assign this one to me and do you have designs somewhere or should twitter just be in white box?

**Comment by zsofimajor** [comment]
@klukacin all the designs are here: https://drive.google.com/open?id=0B78nd8vPZJK3QmxRbXRNb1ZXWlE

**Comment by mojzis** [comment]
This issue was moved to drupalironcamp/website#3
