### ISSUE TITLE
Create vocabularys and terms

### ISSUE THREAD

**Issue by csakiistvan** [drupalironcamp/campsite-2015#13]
See vocab_terms tab on [backlog spreadsheet](https://docs.google.com/a/integralvision.hu/spreadsheets/d/1hxki0UlowliIRCPCKgUcqJfuOWrsi0NcP2yztLzDh0w/edit#gid=1107734566).

**Comment by Sweetchuck** [comment]
I am working on this issue.

This branch is depend on the PR #30 
https://github.com/Sweetchuck/campsite-2015/tree/i13-taxonomy-terms

**Comment by Sweetchuck** [comment]
The _Session type_ vocabulary is belongs to the #8 
and the _Sponsor category_ vocabulary is belongs to the #10
Later we will have to move the vocabulary and the node type into the same module.

**Comment by csakiistvan** [comment]
@Sweetchuck why we have to move into the same module? Why problem is the modules create small tasks?

**Comment by csakiistvan** [comment]
I would like to close this issue, it's incomplete/duplicate. Some vocabulary create on #42, just one missing it's will be create on #10

**Comment by csakiistvan** [comment]
Fix on #44
