### ISSUE TITLE
Cretae Fields to users

### ISSUE THREAD

**Issue by csakiistvan** [drupalironcamp/campsite-2015#2]
About more information see the user fields tab on [backlog spreadsheet](https://docs.google.com/a/integralvision.hu/spreadsheets/d/1hxki0UlowliIRCPCKgUcqJfuOWrsi0NcP2yztLzDh0w/edit#gid=670826284).

**Comment by miromichalicka** [comment]
Do you want to create fields in Profile2?

**Comment by csakiistvan** [comment]
I don't think so, I think we don't need Profile 2

**Comment by csakiistvan** [comment]
Working on this

**Comment by csakiistvan** [comment]
Fixed on #35 PR
