### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by miromichalicka** [drupalironcamp/campsite-2015#31]
An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://ironcamp.dd:8088/install.php?profile=campsite&locale=en&id=1&op=do StatusText: OK ResponseText: Fatal error: Call to undefined function ckeditor_profile_delete() in /Users/mirom/Sites/campsite-2015/docroot/profiles/campsite/campsite.install on line 23

**Comment by csakiistvan** [comment]
the #43 PR is fix that issue, thx @Sweetchuck
