### ISSUE TITLE
Create "Basic page" node type

### ISSUE THREAD

**Issue by csakiistvan** [drupalironcamp/campsite-2015#7]
See node_type tab on [backlog spreadsheet](https://docs.google.com/a/integralvision.hu/spreadsheets/d/1hxki0UlowliIRCPCKgUcqJfuOWrsi0NcP2yztLzDh0w/edit#gid=2043116932).

**Comment by miromichalicka** [comment]
this is created automatically by drupal, isn't it? Or do you want just to put it into feature?

**Comment by csakiistvan** [comment]
From feature I think, it is easier, because we don't use standard profile to this.

**Comment by csakiistvan** [comment]
Fix on #40 PR
