### ISSUE TITLE
Add integration with ticket selling platform

### ISSUE THREAD

**Issue by miromichalicka** [drupalironcamp/campsite-2015#75]
If we are going to sell tickets via eventbrite, use https://www.drupal.org/project/eventbrite_api or https://www.drupal.org/project/eventbrite to create user account on site after ticket is purchased.

**Comment by rinasek** [comment]
We need to check what will we use for ticket sales.

**Comment by miromichalicka** [comment]
neither of modules mentioned before is working because eventbrite deprecated their apis some time last year

**Comment by mojzis** [comment]
This issue was moved to drupalironcamp/website#7
